# Generated by Django 6.0.4 on 2026-04-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
