# Generated by Django 6.0.4 on 2026-04-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('tracking_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
