# Generated by Django 6.0.4 on 2026-04-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_ticket_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
