# Generated by Django 6.0.4 on 2026-04-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_trackinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Priority',
            field=models.CharField(default='Not Selected', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='purchase',
            field=models.CharField(default='Not Selected', max_length=20),
        ),
    ]
