# Generated by Django 6.0.4 on 2026-04-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_ticket_priority_ticket_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Priority',
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
