# Generated by Django 6.0.4 on 2026-04-20 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_ticketcomment_delete_ticketchat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={},
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='user.ticket'),
        ),
    ]
