# Generated by Django 6.0.4 on 2026-04-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_ticketcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
