# Generated by Django 6.0.4 on 2026-04-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_ticketcomment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
