# Generated by Django 6.0.4 on 2026-04-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_adminchat_staffprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_id',
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.purchase')),
            ],
        ),
    ]
