# Generated by Django 6.0.4 on 2026-05-06 05:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_adminchat_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='ticketimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
