# Generated by Django 6.0.4 on 2026-05-06 06:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_ticketcomment_image_alter_ticketimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
